example:
  name: Blog that shows post updates 
  tags:
    - public        # works without Insiders
    - blog          # functionality demonstrated
    - simple        # requires no extra plugins or other magic
    - customization # shows how to customize the theme
  authors:
    alexvoss:
      name: Alex Voss
      description: Collaborator
      ghuser: alexvoss
