example:
  name: Adding a blog to your site
  tags:
    - public        # works without Insiders
    - blog          # functionality demonstrated
    - simple        # requires no extra plugins or other magic
  authors:
    alexvoss:
      name: Alex Voss
      description: Collaborator
      ghuser: alexvoss
