example:
  name: Using built-in browser fonts
  tags:
    - public        # works without Insiders
    - fonts         # functionality demonstrated
    - simple        # uses only Material functionality
  authors:
    alexvoss:
      name: Alex Voss
      description: Collaborator
      ghuser: alexvoss
